### ISSUE TITLE
Add `testifylint` to `golangci-lint`

### ISSUE THREAD

**Issue by knight42** [Antonboom/testifylint#1]
Hi @Antonboom, thanks for writing this useful linter. 

Would you mind adding it to `golangci-lint`(https://golangci-lint.run/contributing/new-linters/#how-to-add-a-public-linter-to-golangci-lint)? I believe it can help a wide range of users.

**Comment by Antonboom** [comment]
Hello @knight42

Thanks for your feedback, it's appreciated.
Linter is already awaiting integration into https://github.com/golangci/golangci-lint/pull/4072.

You can hurry up this request there :)

**Comment by knight42** [comment]
That's great! Thank you!
