### ISSUE TITLE
bool-compare: compares: add Empty And Zero

### ISSUE THREAD

**Issue by ccoVeille** [Antonboom/testifylint#106]
Some people may use testify Zero, Empty, NotZero, and NotEmpty asserters the same way True or False could have been used

**Comment by ccoVeille** [comment]
I thought about it after we closed https://github.com/Antonboom/testifylint/issues/75

Zero and Empty are like True and False, they can be used wrongly

This one is somehow related to #105 as it's about adding zero and empty to existing asserter.

I preferred a dedicated issue as they could be reviewed separately

**Comment by ccoVeille** [comment]
I have a PR almost ready for this one I think, I will finish #105 first

**Comment by Antonboom** [comment]
@ccoVeille, I did not catch what patterns are you talking about?

Can you share specific examples and links to search, thanks

**Comment by ccoVeille** [comment]
My idea was to extend existing checker with strange case people may use as empty/zero could be used the same way that True/False are used in bool compare.

I checked at existing piece of code by using GitHub search and I found nothing relevant.

You seem not likely open to catch this. OK then.
