### ISSUE TITLE
 compares: add Empty And Zero

### ISSUE THREAD

**Issue by ccoVeille** [Antonboom/testifylint#110]
Some people may use testify Zero, Empty, NotZero, and NotEmpty asserters the same way True or False could have been used

**Comment by Antonboom** [comment]
Hi!

Any real examples please, looks like something weird.
I do not want to promote the very strange use of `testify`, even in tests.

**Comment by ccoVeille** [comment]
I failed to find real life example…

Should I nuke #111 completly ? or could we keep the refactoring commits I made ?

**Comment by Antonboom** [comment]
> or could we keep the refactoring commits I made ?

Yes, please, open new PR with refactored part if this change makes sense
Thanks
