### ISSUE TITLE
require-error-is-as: possible broken import when fixing

### ISSUE THREAD

**Issue by ccoVeille** [Antonboom/testifylint#127]
-fix may imply that `errors` package is no longer needed

Here is an example

```go
package main

import (
	"errors"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestWhatever(t *testing.T) {
	_, err := os.UserHomeDir()
	assert.True(t, errors.Is(err, os.ErrDeadlineExceeded))
}
```

when using -fix, `testifylint` will replace `errors.Is` by `assert.ErrorIs`. Here is the result.

```go
package main

import (
	"errors"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestWhatever(t *testing.T) {
	_, err := os.UserHomeDir()
	assert.ErrorIs(t, err, os.ErrDeadlineExceeded)
}
```

But this file is invalid: the `errors` package is no longer needed, launching a `goimport` on it fix it

**Comment by ccoVeille** [comment]
Please note the bug may also occurs with `formatter` checker, if `fmt` package is no longer necessary

**Comment by Antonboom** [comment]
I admit that this is possible.

1. `testifylint` doesn't have to deal with formatting the entire file
2. I don't want to "burden" the linter with logic to detect the use of imports
3. The standard patter of linters usage in combination of `go fmt`, `gofumpt`, `gci`, `goimports`, etc.

So, nothing to do there.
