### ISSUE TITLE
float-compare: questions with best practices 

### ISSUE THREAD

**Issue by mmorel-35** [Antonboom/testifylint#130]
In https://github.com/argoproj/argo-cd/pull/18721/files I applyied float-compare rules .
I have two questions here.
With this first case we have situation 
```go
assert.Equal(t, float64(1), retryCount)
```
This suggestion 
```go
assert.InEpsilon(t, float64(1), retryCount, 0.0001)
```
Having to convert an integer to a float to compare with a float then have to be used with `assert.InDelta` or `assert.InEpsilon`.

What do you think about using 
 ```go
assert.EqualValue(t, 1, retryCount)
```
Maybe this situation indicates a mistyping at the origin so the solution is to change the type of retryCount as a counter is usually an integer.

The other question is about 
```go
assert.Equal(t, liveReplicas, desiredReplicas)
```
I was suggested to use `assert.InEpsilon` but I ended up using

```go
assert.Zero(t, desiredReplicas)
assert.Zero(t, liveReplicas)
```

The reason behind this is that `assert.InEpsilon` doesn’t support having 0 as an expected value. The tricky thing in this situation is that desiredReplicas might not be known in certain cases.

**Comment by Antonboom** [comment]
> Maybe this situation indicates a mistyping at the origin so the solution is to change the type of retryCount as a counter is usually an integer.

Nice point, looks like a feature 👍 

> The reason behind this is that assert.InEpsilon doesn’t support having 0 as an expected value.

Why not `assert.InDelta(t, 0., 0., 0.)`?

**Comment by Antonboom** [comment]
@mmorel-35, I want to transfer this issue into discussion.
But looks like I have no right for it, wtf? )
