### ISSUE TITLE
len: support arr.Len()

### ISSUE THREAD

**Issue by mmorel-35** [Antonboom/testifylint#161]
There are many places where an assertion is done on `arr.Len()` an interface that  `assert.Len()` supports

See. https://github.com/search?q=language%3Ago+testify+%22.Len%28%29%22+path%3A_test.go&type=code

For example 

```go
assert.Equal(t, 0, arr.Len())
assert.Equal(t, 1, arr.Len())
```

Shall be replaced with

```go
assert.Empty(t, arr)
assert.Len(t, arr, 1)
```

**Comment by ccoVeille** [comment]
You might be right by suggesting the usage of empty when equal(t, 0, whatever.Len()) is used only for these 3.

**Comment by ccoVeille** [comment]
But then there is something strange/stupid in testify

https://github.com/stretchr/testify/blob/v1.9.0/assert%2Fassertions.go#L776-L803

Because if a struct implements .Len, we can use assert.Len(t, whatever, 0)

But we cannot use `assert.Empty(t, whatever)`

Maybe it would worth opening an issue on testify

**Comment by ccoVeille** [comment]
I would say Empty should support what Len supports.

The fact the could support the `Len() int` interface might and should be addressed separately, and in another issue

**Comment by Antonboom** [comment]
Hi, guys

Thank you for request.

But `reflect.Value.Len` ([used](https://github.com/stretchr/testify/blob/89cbdd9e7b39eb58896d316a7495597d3aba4371/assert/assertions.go#L784) in `testify`) is not about `Len` interface and this issue no senses.

So `assert.Equal(t, 3, obj.Len())` != `assert.Len(t, obj, 3)`.

Easy test: https://go.dev/play/p/flB3MLf-NUG

Feel free to reopen the issue, if I missed something.
Thanks

**Comment by Antonboom** [comment]
Proof added in https://github.com/Antonboom/testifylint/commit/03ade38d5e5f5cfdb3df10bf986556eb28583c79
