### ISSUE TITLE
encoded-compare: false positive of JSONEq

### ISSUE THREAD

**Issue by Zxilly** [Antonboom/testifylint#198]
https://github.com/Zxilly/go-size-analyzer/blob/d92d0d41ff2ff00977db9940e48d55b58a3968d7/internal/diff/result_test.go#L32

https://github.com/Zxilly/go-size-analyzer/blob/d92d0d41ff2ff00977db9940e48d55b58a3968d7/internal/diff/result_test.go#L61

These compares were meant check if we get the same `*commonResult`.

**Comment by Antonboom** [comment]
@Zxilly fixed, expected in the next patch release of golangci-lint.
thanks!
