### ISSUE TITLE
Don't require `require` for things like `ErrorIs`

### ISSUE THREAD

**Issue by autarch** [Antonboom/testifylint#21]
When checking for the _absence_ of an error, I think it makes sense to always use `require`.

But when checking that an error was returned and that it has specific properties, I don't think there's any reason to use `require` here. In these cases, I don't think that not using `require` increases the chance of a confusing panic in later test code.

**Comment by autarch** [comment]
If changing the existing rule is not possible for backwards compat, maybe it would be possible to add a new off-by-default rule that just lints the "no error" checks?

**Comment by Antonboom** [comment]
Hi, @autarch!

Thank u for report.

1. Do you have any concrete code examples?
2. Did you try the last version of the linter (from `master`)? I merged https://github.com/Antonboom/testifylint/pull/15#issuecomment-1787844177, but do not make tag yet.

**Comment by Antonboom** [comment]
@autarch, hi!

Now you can do
```
testifylint --require-error.fn-patter="^(Errorf?|NoErrorf?)$" ./...
```

or in golangic-lint:
```yml
testifylint:
  require-error:
    fn-pattern: ^(Errorf?|NoErrorf?)$
```
(as soon as will be released)

Thanks.
