### ISSUE TITLE
feature: forbid import of root package `github.com/stretchr/testify`

### ISSUE THREAD

**Issue by dolmen** [Antonboom/testifylint#37]
```
import _ "github.com/stretchr/testify"
```

Import of package `github.com/stretchr/testify` is just an error. This package contains only documentation.

I have noticed that import [in multiple projects](https://pkg.go.dev/github.com/stretchr/testify?tab=importedby). That import was added only to workaround issues with old dependency management tools. This is obsolete in the Go modules era.

**Comment by Antonboom** [comment]
It could be solved by 

- https://golangci-lint.run/usage/linters/#depguard
- https://golangci-lint.run/usage/linters/#forbidigo

but I'll think about adding it to the linter 🤔

**Comment by dolmen** [comment]
I'm also tempted to add this to the package:
```
func init() {
    panic("package github.com/stretchr/testify must not be imported: it has no content")
}
```

**Comment by Antonboom** [comment]
Also
https://github.com/search?q=%22_+%5C%22github.com%2Fstretchr%2Ftestify%5C%22%22&type=code&p=1
