### ISSUE TITLE
feature: forbid import of testify packages as `_`

### ISSUE THREAD

**Issue by dolmen** [Antonboom/testifylint#38]
```
import _ "github.com/stretchr/testify/assert"
```

Import of testify packages (`assert`, `require`, `suite`, `mock`, `http`) as `_` is useless: those package don't do `init` magic.

They might have been imported like that in the past to workaround issues in dependency management tools (see the related case #37) but, now, in the Go modules era, this is obsolete.

Here are some cases in the wild:
* on GitHub: [`import _ "github.com/stretchr/testify/assert"`](https://github.com/search?q=%22import+_+%5C%22github.com%2Fstretchr%2Ftestify%2Fassert%5C%22%22&type=code)
* on GitHub: [`_ "github.com/stretchr/testify/assert"`](https://github.com/search?q=%22_+%5C%22github.com%2Fstretchr%2Ftestify%2Fassert%5C%22%22&type=code)
* on GitHub: [`_ "github.com/stretchr/testify/require"`](https://github.com/search?q=%22_+%5C%22github.com%2Fstretchr%2Ftestify%2Frequire%5C%22%22&type=code)
* on GitHub: [`_ "github.com/stretchr/testify/suite"`](https://github.com/search?q=%22_+%5C%22github.com%2Fstretchr%2Ftestify%2Fsuite%5C%22%22&type=code)
* on GitHub: [`_ "github.com/stretchr/testify/mock"`](https://github.com/search?q=%22_+%5C%22github.com%2Fstretchr%2Ftestify%2Fmock%5C%22%22&type=code)
* on GitHub: [`_ "github.com/stretchr/testify/http"`](https://github.com/search?q=%22_+%5C%22github.com%2Fstretchr%2Ftestify%2Fhttp%5C%22%22&type=code)

**Comment by hendrywiranto** [comment]
may I take this if this feature is desired?

**Comment by Antonboom** [comment]
@hendrywiranto, yes

it looks as enabled by default `checkers.AdvancedChecker`
feel free to ask questions :)
