### ISSUE TITLE
len: false positives for `assert.Equal(t, len(want), got)`

### ISSUE THREAD

**Issue by sgleizes** [Antonboom/testifylint#40]
When the **expected** value is a len, testifylint should not suggest to replace the assertion with `assert.Len`, as it is not equivalent, since the actual value is **not** a len.
For example: `assert.Equal(t, len(want), got)`

**Comment by Antonboom** [comment]
@sgleizes, hi!

Did you try the last version of `testifylint`?
Separately from `golangci-lint`.

It was fixed, but not released yet.

**Comment by sgleizes** [comment]
Hi,

I did only try via golangci-lint indeed. Glad to see it's already fixed.
I will wait for the next release to remove the `//nolint`s.

Thanks

**Comment by Antonboom** [comment]
Duplicate of https://github.com/Antonboom/testifylint/issues/9
