### ISSUE TITLE
exception: Don't suggest `require` inside an http.Handler

### ISSUE THREAD

**Issue by abhinav** [Antonboom/testifylint#73]
`require.NoError` and friends terminate the current goroutine.
This is undesirable for assertions specified inside HTTP handlers—like with `httptest.NewServer`:

```go
srv := httptest.NewServer(http.HandlerFunc(func(hres http.ResponseWriter, hreq *http.Request) {
  // ...
  var req MyRequest
  err := json.NewDecoder(hreq.Body).Decode(req)
  if !assert.NoError(t, err) {
    return
  }
  // ...
})
```

If we switch the `assert` above to `require`, on failure, the HTTP handler goroutine will be terminated.
Depending on how the test is calling this handler, the test will likely freeze until it hits a timeout.

While it's impossible for testifylint to know "this assertion is inside a handler" with 100% accuracy, it may not be too difficult to catch the common case: is this a function or method with the signature `func(http.ResponseWriter, *http.Request)`.

So my proposal is this:
If an assertion is inside an `http.Handler`-shaped function or method, do not recommend `require`.

**Comment by Antonboom** [comment]
hi, @abhinav 

thank you for request.
related to https://github.com/Antonboom/testifylint/issues/66#issuecomment-1975066983

looks like I should reconsider my decision
