### ISSUE TITLE
regexp: simplify `assert.Regexp(t, regexp.MustCompile)`

### ISSUE THREAD

**Issue by ccoVeille** [Antonboom/testifylint#82]
@dolmen post helped me to spot a new checker that could be added

https://github.com/Antonboom/testifylint/issues/81#issuecomment-2060618745

assert.Regexp(t, regex.MustCompile("whatever")… could be simplified into assert.Regexp(t, "whatever"…

I spotted it here
https://github.com/SCP002/m3u_merge_astra/blob/9ae08f40f415292bf646a2dd7811f4d5d799dea6/src/util/logger/logger_test.go#L23

**Comment by ccoVeille** [comment]
Also cc @kevinburkesegment who somehow initiated my discovery

Related: stretchr/testify#1585

**Comment by ccoVeille** [comment]
> Grafana has a fork from regexp, see https://github.com/grafana/regexp
> 
> It might be intrested to suggest it for the standard library and grafana’s version as well ?

I'm unsure to get your point.

There are some interesting lib for regexp.

But, here we are in a linter specialized in: tests (so perf is not the priority) and testify.

Testify has an asserter for Regexp.
This issue is about converting

```go
assert.Regexp(t, regex.MustCompile("whatever"))

// simplified

assert.Regexp(t, "whatever"…
```

**Comment by kevinburkesegment** [comment]
I do not think that adding a new dependency would simplify things

**Comment by ccoVeille** [comment]
Now, I get it.

I didn't check the implementation, but I'm doubtful `assert.Regexp` works with something else than std lib.

But then, why not, did you find examples of such usage?

**Comment by Antonboom** [comment]
Please, stop this discussion.
`testifylint` should work with std lib only or libs that inherited from testify's assertions signatures.
