### ISSUE TITLE
negative-positive: support typed `0`

### ISSUE THREAD

**Issue by ccoVeille** [Antonboom/testifylint#94]
another yet [case](https://github.com/jaegertracing/jaeger/pull/5134/files#diff-83ecac470d767b6e86892d42d2a07581549b6280e355fb316c2e30332bd9d9d1R123) of `assert.Positive`:
```
assert.Greater(t, gs[lastValueLogCleanedName], int64(0))
```

_Originally posted by @Antonboom in https://github.com/Antonboom/testifylint/issues/93#issuecomment-2132368054_

The idea is to complete the linter added with #76

**Comment by ccoVeille** [comment]
I have found this one also in the quoted PR


```go
        assert.Greater(t, stopwatch.ElapsedTime(), time.Duration(0))
```

I'm curious how testifylint behaves right now

**Comment by ccoVeille** [comment]
Just to make sure you wanted to talk about typed 0 ?

I'm unsure what the typed nil could refer to

**Comment by ccoVeille** [comment]
![8tbabj.jpg](https://github.com/Antonboom/testifylint/assets/3875889/f874084d-ba2f-489a-96b5-f4ba256fda20)

**Comment by Antonboom** [comment]
My bad, title is fixed 👌

**Comment by ccoVeille** [comment]
@Antonboom I'm looking at the code and I see similarities between

isIntNumber and isIntBasicLit

https://github.com/Antonboom/testifylint/blob/master/internal/checkers/helpers_basic_type.go#L18-L31

I don't get the difference of comparing the number to its Sprintf value.

The only use case, I can think about is -0 vs 0, but then I don't understand

I looked when the `Sprintf("%d", v) == v` was introduced and I found d6f0ef8f

But I see no reason to add it in the context of this commit, do you have some context about it, because otherwise I might refactor a bit isIntBasicLit
